name: Execute Tests on PR
on:
  push:
  pull_request:
    branches: [main]

jobs:

  runUnitTest:
    name: Execute Unit/Widget tests
  
    runs-on: macos-latest
    steps:
    
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Setup Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    
    - name: pub get
      run: flutter pub get
    
    - name: pub upgrade
      run: flutter pub upgrade --major-versions

    - name: Lint
      run: dart format --output=none --set-exit-if-changed .
    
    - name: dart anaylze
      run: dart analyze
    
    - name: flutter analyze
      run: flutter analyze

    # - name: Run Unit Tests / Widget Tests
    #   run: flutter test
